### ISSUE TITLE
Always get 401

### ISSUE THREAD

**Issue by davidtim** [m-alfan/api-yii2-boilerplate#2]
Hello, I just clone your project. Already logged-in and get the token. but when i try to paste that token to get user info or news i always got 401.

**Comment by m-alfan** [comment]
just want to make sure, have you watch this video https://www.youtube.com/watch?v=TPRfzmTeTXY ?

**Comment by davidtim** [comment]
Yes, I have watched it. I found out why. The reason is that I use vhost.
When I use simple localhost it work find.

**Comment by m-alfan** [comment]
Please send your debug log in runtime/logs/app.log

**Comment by davidtim** [comment]
`2018-04-19 11:52:06 [127.0.0.1][-][-][error][yii\web\HttpException:401] yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:91
Stack trace:
#0 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(74): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/ActionFilter.php(75): yii\filters\auth\AuthMethod->beforeAction(Object(yii\base\InlineAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#3 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Array, Object(yii\base\ActionEvent))
#4 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/Controller.php(272): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/web/Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#6 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/Controller.php(154): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#7 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('me', Array)
#8 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('v1/auth/me', Array)
#9 /Applications/MAMP/htdocs/hrapi/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /Applications/MAMP/htdocs/hrapi/web/index.php(19): yii\base\Application->run()
#11 {main}`

**Comment by davidtim** [comment]
this is what i get when using vhost(api.local/web/)

**Comment by m-alfan** [comment]
Ok, maybe this can solve:
check your token https://jwt.io/  - in PAYLOAD column
 ```
{
  "iss": "[same or not with your vhost]",
  "aud": "[same or not with your vhost]",
  "iat": 1524114031,
  "nbf": 1524114031,
  "exp": 1524132031,
  "jti": "[secret / authKey user]"
}
```
if it not same you can generate token with login again in your vhost or change **iss** and **aud** in jwt.io

**Comment by davidtim** [comment]
yes, it's the same

> `{
  "iss": "http://hrapi.local",
  "aud": "http://hrapi.local",
  "iat": 1524115536,
  "nbf": 1524115536,
  "exp": 1524133536,
  "jti": "kFvZUEN_K5ZcuthtAv3pvHaB7_IoTN9h"
}`
<img width="322" alt="screen shot 2018-04-19 at 12 27 45 pm" src="https://user-images.githubusercontent.com/4997933/38972820-17c1b7ec-43cd-11e8-94da-40f9e378753f.png">

**Comment by m-alfan** [comment]
Actually, what vhost you use **hrapi.local** / **api.local**

if you always get a 401 response, that's a sign of an invalid token,

to get the data you have to put the valid token in the header content "Authorization": "Bearer [your token]", for example you can generate new token (jwt) directly without having to login in jwt.io site

**Comment by davidtim** [comment]
i use hrapi.local. I found out that if i use vhost the Authentication header will not send. I'm trying to find out why.

**Comment by davidtim** [comment]
ok i giveup. now i'm running localhost

**Comment by m-alfan** [comment]
sorry @davidtim i can't help solve your problem

**Comment by davidtim** [comment]
No need to sorry man! Thank you for your wonderful boilerplate!
